//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EQService.IServiceEmail")]
    public interface IServiceEmail
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmail/GetServiceStatus", ReplyAction="http://tempuri.org/IServiceEmail/GetServiceStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDDescriptionPair))]
        System.Threading.Tasks.Task<EQService.GetServiceStatusResponse> GetServiceStatusAsync(EQService.GetServiceStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmail/GetStatus", ReplyAction="http://tempuri.org/IServiceEmail/GetStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDDescriptionPair))]
        System.Threading.Tasks.Task<EQService.GetStatusResponse> GetStatusAsync(EQService.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmail/Add", ReplyAction="http://tempuri.org/IServiceEmail/AddResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDDescriptionPair))]
        System.Threading.Tasks.Task<EQService.AddResponse> AddAsync(EQService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmail/GetLog", ReplyAction="http://tempuri.org/IServiceEmail/GetLogResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDDescriptionPair))]
        System.Threading.Tasks.Task<EQService.GetLogResponse> GetLogAsync(EQService.GetLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmail/Load", ReplyAction="http://tempuri.org/IServiceEmail/LoadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDDescriptionPair))]
        System.Threading.Tasks.Task<EQService.LoadResponse> LoadAsync(EQService.LoadRequest request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuditLogAction))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Synetec.AuditLog")]
    public partial class IDDescriptionPair
    {
        
        private string _descriptionField;
        
        private int _idField;
        
        private bool _preventLookupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string _description
        {
            get
            {
                return this._descriptionField;
            }
            set
            {
                this._descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int _id
        {
            get
            {
                return this._idField;
            }
            set
            {
                this._idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool _preventLookup
        {
            get
            {
                return this._preventLookupField;
            }
            set
            {
                this._preventLookupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Synetec.AuditLog")]
    public partial class AuditLogAction : IDDescriptionPair
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Synetec.AuditLog")]
    public partial class AuditLog
    {
        
        private AuditLogAction actionField;
        
        private System.DateTime actionDateTimeField;
        
        private bool actionDateTimeFieldSpecified;
        
        private string descriptionField;
        
        private string emailIDField;
        
        private string userLoginField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AuditLogAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ActionDateTime
        {
            get
            {
                return this.actionDateTimeField;
            }
            set
            {
                this.actionDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionDateTimeSpecified
        {
            get
            {
                return this.actionDateTimeFieldSpecified;
            }
            set
            {
                this.actionDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmailID
        {
            get
            {
                return this.emailIDField;
            }
            set
            {
                this.emailIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string UserLogin
        {
            get
            {
                return this.userLoginField;
            }
            set
            {
                this.userLoginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EQS.Core")]
    public partial class EmailAttachment
    {
        
        private byte[] attachedFileField;
        
        private string attachedFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] AttachedFile
        {
            get
            {
                return this.attachedFileField;
            }
            set
            {
                this.attachedFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AttachedFileName
        {
            get
            {
                return this.attachedFileNameField;
            }
            set
            {
                this.attachedFileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetServiceStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientPassword;
        
        public GetServiceStatusRequest()
        {
        }
        
        public GetServiceStatusRequest(string clientLogin, string clientPassword)
        {
            this.clientLogin = clientLogin;
            this.clientPassword = clientPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetServiceStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EQService.ArrayOfXElement GetServiceStatusResult;
        
        public GetServiceStatusResponse()
        {
        }
        
        public GetServiceStatusResponse(EQService.ArrayOfXElement GetServiceStatusResult)
        {
            this.GetServiceStatusResult = GetServiceStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string value;
        
        public GetStatusRequest()
        {
        }
        
        public GetStatusRequest(string value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetStatusResult;
        
        public GetStatusResponse()
        {
        }
        
        public GetStatusResponse(string GetStatusResult)
        {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appAccountLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appAccountPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emailUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string toAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public bool isHTML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EQS.Core")]
        public EQService.EmailAttachment[] attachments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fromAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fromName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bccAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ccAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public int priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public System.DateTime sendDateTime;
        
        public AddRequest()
        {
        }
        
        public AddRequest(string appAccountLogin, string appAccountPassword, string emailUserName, string toAddress, string subject, string body, bool isHTML, EQService.EmailAttachment[] attachments, string fromAddress, string fromName, string bccAddress, string ccAddress, int priority, System.DateTime sendDateTime)
        {
            this.appAccountLogin = appAccountLogin;
            this.appAccountPassword = appAccountPassword;
            this.emailUserName = emailUserName;
            this.toAddress = toAddress;
            this.subject = subject;
            this.body = body;
            this.isHTML = isHTML;
            this.attachments = attachments;
            this.fromAddress = fromAddress;
            this.fromName = fromName;
            this.bccAddress = bccAddress;
            this.ccAddress = ccAddress;
            this.priority = priority;
            this.sendDateTime = sendDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddResult;
        
        public AddResponse()
        {
        }
        
        public AddResponse(string AddResult)
        {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLog", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLogRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string emailID;
        
        public GetLogRequest()
        {
        }
        
        public GetLogRequest(string emailID)
        {
            this.emailID = emailID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLogResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLogResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Synetec.AuditLog")]
        public EQService.AuditLog[] GetLogResult;
        
        public GetLogResponse()
        {
        }
        
        public GetLogResponse(EQService.AuditLog[] GetLogResult)
        {
            this.GetLogResult = GetLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Load", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appAccountLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appAccountPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string emailID;
        
        public LoadRequest()
        {
        }
        
        public LoadRequest(string appAccountLogin, string appAccountPassword, string emailID)
        {
            this.appAccountLogin = appAccountLogin;
            this.appAccountPassword = appAccountPassword;
            this.emailID = emailID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EQService.ArrayOfXElement LoadResult;
        
        public LoadResponse()
        {
        }
        
        public LoadResponse(EQService.ArrayOfXElement LoadResult)
        {
            this.LoadResult = LoadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IServiceEmailChannel : EQService.IServiceEmail, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ServiceEmailClient : System.ServiceModel.ClientBase<EQService.IServiceEmail>, EQService.IServiceEmail
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceEmailClient() : 
                base(ServiceEmailClient.GetDefaultBinding(), ServiceEmailClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Basic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceEmailClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceEmailClient.GetBindingForEndpoint(endpointConfiguration), ServiceEmailClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceEmailClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceEmailClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceEmailClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceEmailClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceEmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EQService.GetServiceStatusResponse> EQService.IServiceEmail.GetServiceStatusAsync(EQService.GetServiceStatusRequest request)
        {
            return base.Channel.GetServiceStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<EQService.GetServiceStatusResponse> GetServiceStatusAsync(string clientLogin, string clientPassword)
        {
            EQService.GetServiceStatusRequest inValue = new EQService.GetServiceStatusRequest();
            inValue.clientLogin = clientLogin;
            inValue.clientPassword = clientPassword;
            return ((EQService.IServiceEmail)(this)).GetServiceStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EQService.GetStatusResponse> EQService.IServiceEmail.GetStatusAsync(EQService.GetStatusRequest request)
        {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<EQService.GetStatusResponse> GetStatusAsync(string value)
        {
            EQService.GetStatusRequest inValue = new EQService.GetStatusRequest();
            inValue.value = value;
            return ((EQService.IServiceEmail)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EQService.AddResponse> EQService.IServiceEmail.AddAsync(EQService.AddRequest request)
        {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<EQService.AddResponse> AddAsync(string appAccountLogin, string appAccountPassword, string emailUserName, string toAddress, string subject, string body, bool isHTML, EQService.EmailAttachment[] attachments, string fromAddress, string fromName, string bccAddress, string ccAddress, int priority, System.DateTime sendDateTime)
        {
            EQService.AddRequest inValue = new EQService.AddRequest();
            inValue.appAccountLogin = appAccountLogin;
            inValue.appAccountPassword = appAccountPassword;
            inValue.emailUserName = emailUserName;
            inValue.toAddress = toAddress;
            inValue.subject = subject;
            inValue.body = body;
            inValue.isHTML = isHTML;
            inValue.attachments = attachments;
            inValue.fromAddress = fromAddress;
            inValue.fromName = fromName;
            inValue.bccAddress = bccAddress;
            inValue.ccAddress = ccAddress;
            inValue.priority = priority;
            inValue.sendDateTime = sendDateTime;
            return ((EQService.IServiceEmail)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EQService.GetLogResponse> EQService.IServiceEmail.GetLogAsync(EQService.GetLogRequest request)
        {
            return base.Channel.GetLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<EQService.GetLogResponse> GetLogAsync(string emailID)
        {
            EQService.GetLogRequest inValue = new EQService.GetLogRequest();
            inValue.emailID = emailID;
            return ((EQService.IServiceEmail)(this)).GetLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EQService.LoadResponse> EQService.IServiceEmail.LoadAsync(EQService.LoadRequest request)
        {
            return base.Channel.LoadAsync(request);
        }
        
        public System.Threading.Tasks.Task<EQService.LoadResponse> LoadAsync(string appAccountLogin, string appAccountPassword, string emailID)
        {
            EQService.LoadRequest inValue = new EQService.LoadRequest();
            inValue.appAccountLogin = appAccountLogin;
            inValue.appAccountPassword = appAccountPassword;
            inValue.emailID = emailID;
            return ((EQService.IServiceEmail)(this)).LoadAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Basic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Basic))
            {
                return new System.ServiceModel.EndpointAddress("http://test.eqs.synetec.co.uk/EQS.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceEmailClient.GetBindingForEndpoint(EndpointConfiguration.Basic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceEmailClient.GetEndpointAddress(EndpointConfiguration.Basic);
        }
        
        public enum EndpointConfiguration
        {
            
            Basic,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
